### PR TITLE
Improve the website's accessibility

### PR DESCRIPTION
**Pull request by nedjwab**
### ✨ In This Pull Request I improved My website's accessibility ✨:
- **Page titles**:No issue Found ✔.
- **Image text alternatives**: Change my 'alt' in [Skills section](https://github.com/nedjwab/MyPortfolio/commit/0eeeebe05bf4a116c6f0b65d5fdcf76396423207#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L155) more meaningful text.
- **Text Headings**:Changed the Textearea [Heading ](https://github.com/nedjwab/MyPortfolio/commit/0eeeebe05bf4a116c6f0b65d5fdcf76396423207#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L113).Replace `h3` by `h2` .
- **Color Contrast**:Made changes to [Logo](https://github.com/nedjwab/MyPortfolio/pull/18/files#diff-b78be019f1dc6d57753ea900c3805b114cd53ab7c0db836cc081836df1b99b7aL2) and [Buttons ](https://github.com/nedjwab/MyPortfolio/pull/18/files#diff-b78be019f1dc6d57753ea900c3805b114cd53ab7c0db836cc081836df1b99b7aL153).
- **Resize**: No issue found ✔.
- **Interaction**:Removed the `outline:None` from the TextArea in [Contact form](https://github.com/nedjwab/MyPortfolio/commit/0eeeebe05bf4a116c6f0b65d5fdcf76396423207#diff-b78be019f1dc6d57753ea900c3805b114cd53ab7c0db836cc081836df1b99b7aL447).
- **Moving Content**: No issue found. My website doesn't include Moving Content ✔
- **Multimedia**: No issue found. My website doesn't include videos or audio ✔
- **The basic structure of the page**: No issue Found ✔

### CODE REVIEW

**Review by omar-muhamad — CHANGES_REQUESTED** [review]
.

**Review by omar-muhamad — CHANGES_REQUESTED** [review]
# Changes Required ♻️
### Hi Team,

Nice job, you are almost there.



## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

You did great so far but you have color contrast issues in 3 different places so Please fix them.
- [ ] All project cards technologies 

image

- [ ] All project cards buttons ( normal, hover, and active) interaction.

image

- [ ] All Languages, Frameworks, and skills.

image

You can check the contrast for your website using this [link](https://www.aditus.io/button-contrast-checker/)

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by nedjwab** [comment]
@Omar-Muhamad thank you for your feedback 👍 . But maybe you made a mistake these screenshots are not from my project 😁

**Review by akucintavalent — APPROVED** [review]
# Approved 👏 

Hi there, @nedjwab 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

To Highlight: 
- Everything is perfect!

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashboard. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

**Pull request merged**
